/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LayoutRouteRouteImport } from './routes/_layout/route'
import { Route as LayoutIndexRouteRouteImport } from './routes/_layout/index/route'
import { Route as LayoutAboutRouteRouteImport } from './routes/_layout/about/route'
import { Route as LayoutContactUsRouteRouteImport } from './routes/_layout/contact-us/route'

const LayoutRouteRoute = LayoutRouteRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRouteRoute = LayoutIndexRouteRouteImport.update({
  id: '/',
  path: '',
  getParentRoute: () => LayoutRouteRoute,
} as any)
const LayoutAboutRouteRoute = LayoutAboutRouteRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => LayoutRouteRoute,
} as any)
const LayoutContactUsRouteRoute = LayoutContactUsRouteRouteImport.update({
  id: '/contact-us',
  path: '/contact-us',
  getParentRoute: () => LayoutRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof LayoutIndexRouteRoute
  '/about': typeof LayoutAboutRouteRoute
  '/contact-us': typeof LayoutContactUsRouteRoute
}
export interface FileRoutesByTo {
  '/': typeof LayoutIndexRouteRoute
  '/about': typeof LayoutAboutRouteRoute
  '/contact-us': typeof LayoutContactUsRouteRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteRouteWithChildren
  '/_layout/': typeof LayoutIndexRouteRoute
  '/_layout/about': typeof LayoutAboutRouteRoute
  '/_layout/contact-us': typeof LayoutContactUsRouteRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/about' | '/contact-us'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/contact-us'
  id:
    | '__root__'
    | '/_layout'
    | '/_layout/'
    | '/_layout/about'
    | '/_layout/contact-us'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRouteRoute: typeof LayoutRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteRouteImport
      parentRoute: typeof LayoutRouteRoute
    }
    '/_layout/about': {
      id: '/_layout/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof LayoutAboutRouteRouteImport
      parentRoute: typeof LayoutRouteRoute
    }
    '/_layout/contact-us': {
      id: '/_layout/contact-us'
      path: '/contact-us'
      fullPath: '/contact-us'
      preLoaderRoute: typeof LayoutContactUsRouteRouteImport
      parentRoute: typeof LayoutRouteRoute
    }
  }
}

interface LayoutRouteRouteChildren {
  LayoutIndexRouteRoute: typeof LayoutIndexRouteRoute
  LayoutAboutRouteRoute: typeof LayoutAboutRouteRoute
  LayoutContactUsRouteRoute: typeof LayoutContactUsRouteRoute
}

const LayoutRouteRouteChildren: LayoutRouteRouteChildren = {
  LayoutIndexRouteRoute: LayoutIndexRouteRoute,
  LayoutAboutRouteRoute: LayoutAboutRouteRoute,
  LayoutContactUsRouteRoute: LayoutContactUsRouteRoute,
}

const LayoutRouteRouteWithChildren = LayoutRouteRoute._addFileChildren(
  LayoutRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  LayoutRouteRoute: LayoutRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
